apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-for-svc
  # annotations:
    # kubernetes.io/change-cause: version 1.10.1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-for-svc
  template:
    metadata:
      labels:
        app: nginx-for-svc
    spec:
      containers:
      - name: nginx-for-svc
        image: kingdom0220/nodejs:latest
        ports:
        - containerPort: 8000
